### ISSUE TITLE
Invalid cert error but tasks keep executing

### ISSUE THREAD

**Issue by chadlung** [zinic/atom-nuke#16]
If I write a crawler and pick a feed server that uses SSL and I don't have the cert installed then an error is thrown.  When the invalid cert error is thrown all tasks related to that SSL feed should shutdown rather than continue to run and throw errors.

**Comment by chadlung** [comment]
This is also related to this issue.  If you provide an invalid endpoint errors are thrown (see below).  This is a bit tricky as the endpoint could've gone down temporarily so I wouldn't want it to stop executing in case it comes back up, but then again maybe if the endpoint was bad to begin with I would want to stop running the task.  Maybe new tasks could take a parameter (toggle) to continue on a failed poll or to just stop..?

12/08/03 22:24:31 ERROR manager.ManagedTaskImpl: Failed to poll ATOM feed: "http://localhost:8081/namespace/feed/"
net.jps.nuke.source.AtomSourceException: Failed to poll ATOM feed: "http://localhost:8081/namespace/feed/"

**Comment by zinic** [comment]
This might be better serviced through being able to specify an error/exception handler. What do you think?

**Comment by chadlung** [comment]
That would be good. It could be caught and the errant task could be cancelled in the case of multiple running tasks.

**Comment by zinic** [comment]
Check. Scheduling this for the 1.0 milestone.

**Comment by zinic** [comment]
Still looking at error handling but I'm going to mark this is do not fix. Logging has been enhanced along with giving an ATOMSource the ability to communicate failure and the notion that it should be de-registered.
